### ISSUE TITLE
Integrate Jap-Ger translation from JMDict

### ISSUE THREAD

**Issue by ghost** [AnkiUniversal/NLP-Japanese-Dictionary#2]
Hello,

I would like to investigate and discuss the implementation of the german translation into NLP Japanese Dictionary. 
Any thoughts or objections regarding this?

**Comment by AnkiUniversal** [comment]
Well, there're multiple ways to do this. But the easiest way is to use **Sense** classes, because JMDict will store **Gloss** of different languages in the same sense element. 

**1.** Firstly, you will need to include German into the main dictionary database: **Resource\DictConvert\JapEngDict.db** In this SQLite database file, there will be a column named **SenseElement**, which stores XML <sense> tag of JMDict in JSON format. For example:
[
  {
    "gloss": "no!; no no!; no, not at all",
    "pos": "interjection",
    "misc": "word usually written using kana alone",
    "xref": "嫌々・いやいや・3"
  }
]
So you will have to insert the German translation from JMDict into this column. For example:
[
  {
    "glossGER": "Nein",
    "gloss": "no!; no no!; no, not at all",
    "pos": "interjection",
    "misc": "word usually written using kana alone",
    "xref": "嫌々・いやいや・3"
  }
]

**2.** Revise class **Core\JmdictElements\SenseElement.cs**: Add a public properties for German (ex.  public string GlossGer { get; set; } ). Then init this property in the constructor:
if (senseElement.TryGetValue("glossGer", out value))
                GlossGer = value.ToString();

**3.** In **Models\SenseElementModel.cs**: Add a string property for GlossGer and add it into the constructor. You will also need to revise **ViewModels\SenseElementViewModel.cs** to reflect the change in constructor.

**4.** Finally, **In Models\SenseElementRichTextModel.cs** Add the way to want to display GlossGer (see line 71-74 to see how English is displayed) into the constructor and reflect this change in **ViewModel\SenseElementRichTextViewModel.cs**

I might miss some minor things but basically this will cover all necessary steps.

**Comment by ghost** [comment]
Thanks for the information.
I will have a look into it.
